{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mala2017",
    "module": "testpublish",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "testpublish-1.0.0.aar",
          "url": "testpublish-1.0.0.aar",
          "size": 779,
          "sha512": "b7d23dc8737c0aad5220fea3c1687630ecdb7812d8d4d9002d5c75f0f990dc6a34a5e9ebea01cd50ee9a859ab9b6917da06654a3438b2746db9568e7f5e84a77",
          "sha256": "a63326f8dc683393f75d77657cc22cb4f7f70d4b80f7c04ef59c322e4f247bfb",
          "sha1": "67c9551fc247115eddc5ff12f6e6d6ea4a6ef7c8",
          "md5": "6bb5abc76cabb1d23874fd86b9c7a833"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "testpublish-1.0.0.aar",
          "url": "testpublish-1.0.0.aar",
          "size": 779,
          "sha512": "b7d23dc8737c0aad5220fea3c1687630ecdb7812d8d4d9002d5c75f0f990dc6a34a5e9ebea01cd50ee9a859ab9b6917da06654a3438b2746db9568e7f5e84a77",
          "sha256": "a63326f8dc683393f75d77657cc22cb4f7f70d4b80f7c04ef59c322e4f247bfb",
          "sha1": "67c9551fc247115eddc5ff12f6e6d6ea4a6ef7c8",
          "md5": "6bb5abc76cabb1d23874fd86b9c7a833"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testpublish-1.0.0-sources.jar",
          "url": "testpublish-1.0.0-sources.jar",
          "size": 551,
          "sha512": "f2f69f7280357dcf46625b4735007f866e33bc725316a49a2a8933d07fc7e2a55ff3f0aa92ca7ad4f7084ee48025bd1cd45b72fb6b080d8286353ad5a231802a",
          "sha256": "1b563f39fc83dff3c8738d47b11b627cf5ee04b98e066fc0b8f2d4f33b522159",
          "sha1": "eab470e02c49d974df217418241b147b756ca90a",
          "md5": "2941d53dfc6d487e6cb39e506eeb7f54"
        }
      ]
    }
  ]
}
